from .models import DeviceType, Protocol, DestinationType, PolicyRule, PolicyType, Confidence

POLICY_RULES: list[PolicyRule] = [
    PolicyRule(
        rule_id="CAM-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.CAMERA,
        description="Cameras must not use remote shell protocols (SSH, Telnet)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value]},
    ),
    PolicyRule(
        rule_id="CAM-PROTO-002",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.CAMERA,
        description="Cameras must not use file transfer protocols (FTP)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="CAM-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.CAMERA,
        description="Cameras must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="CAM-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.CAMERA,
        description="Camera bytes_sent must not exceed 500KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 500_000},
    ),
    PolicyRule(
        rule_id="CAM-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.CAMERA,
        description="Camera session duration must not exceed 30 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 30.0},
    ),
    PolicyRule(
        rule_id="CAM-DIR-001",
        policy_type=PolicyType.TRAFFIC_DIRECTION,
        device_type=DeviceType.CAMERA,
        description="Camera traffic must be outbound-heavy",
        confidence=Confidence.MEDIUM,
        parameters={"max_inbound_ratio": 2.0},
    ),
    PolicyRule(
        rule_id="PRT-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.PRINTER,
        description="Printers must not use remote shell protocols (SSH, Telnet)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value]},
    ),
    PolicyRule(
        rule_id="PRT-PROTO-002",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.PRINTER,
        description="Printers must not use file transfer protocols (FTP)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="PRT-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.PRINTER,
        description="Printers must not contact external internet",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value, DestinationType.TRUSTED_CLOUD.value]},
    ),
    PolicyRule(
        rule_id="PRT-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.PRINTER,
        description="Printer bytes_sent must not exceed 50KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 50_000},
    ),
    PolicyRule(
        rule_id="PRT-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.PRINTER,
        description="Printer session duration must not exceed 10 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 10.0},
    ),
    PolicyRule(
        rule_id="RTR-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.ROUTER,
        description="Routers must not use insecure management protocols (Telnet, FTP)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.TELNET.value, Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="RTR-PROTO-002",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.ROUTER,
        description="Routers must not initiate SSH outbound",
        confidence=Confidence.MEDIUM,
        parameters={"blocked_protocols": [Protocol.SSH.value]},
    ),
    PolicyRule(
        rule_id="RTR-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.ROUTER,
        description="Routers must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="RTR-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.ROUTER,
        description="Router control sessions must not exceed 5 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 5.0},
    ),
    PolicyRule(
        rule_id="RTR-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.ROUTER,
        description="Router bytes_sent must not exceed 10KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 10_000},
    ),
    PolicyRule(
        rule_id="LPT-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.LAPTOP,
        description="Laptops must not use insecure Telnet protocol",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.TELNET.value]},
    ),
    PolicyRule(
        rule_id="LPT-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.LAPTOP,
        description="Laptop bytes_sent must not exceed 1MB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 1_000_000},
    ),
    PolicyRule(
        rule_id="LPT-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.LAPTOP,
        description="Laptop session duration must not exceed 120 seconds",
        confidence=Confidence.LOW,
        parameters={"max_duration": 120.0},
    ),
    PolicyRule(
        rule_id="STV-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.SMART_TV,
        description="Smart TVs must not use remote shell protocols (SSH, Telnet)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value]},
    ),
    PolicyRule(
        rule_id="STV-PROTO-002",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.SMART_TV,
        description="Smart TVs must not use file transfer protocols (FTP)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="STV-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.SMART_TV,
        description="Smart TVs must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="STV-DIR-001",
        policy_type=PolicyType.TRAFFIC_DIRECTION,
        device_type=DeviceType.SMART_TV,
        description="Smart TV traffic must be inbound-heavy",
        confidence=Confidence.MEDIUM,
        parameters={"max_outbound_ratio": 3.0},
    ),
    PolicyRule(
        rule_id="STV-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.SMART_TV,
        description="Smart TV bytes_sent must not exceed 100KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 100_000},
    ),
    PolicyRule(
        rule_id="THM-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.THERMOSTAT,
        description="Thermostats must not use remote shell or file transfer protocols",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value, Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="THM-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.THERMOSTAT,
        description="Thermostats must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="THM-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.THERMOSTAT,
        description="Thermostat bytes_sent must not exceed 10KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 10_000},
    ),
    PolicyRule(
        rule_id="THM-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.THERMOSTAT,
        description="Thermostat sessions must not exceed 10 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 10.0},
    ),
    PolicyRule(
        rule_id="DLK-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.SMART_DOOR_LOCK,
        description="Smart door locks must not use SSH, Telnet, or FTP",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value, Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="DLK-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.SMART_DOOR_LOCK,
        description="Smart door locks must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="DLK-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.SMART_DOOR_LOCK,
        description="Door lock bytes_sent must not exceed 5KB per session",
        confidence=Confidence.HIGH,
        parameters={"field": "bytes_sent", "max_value": 5_000},
    ),
    PolicyRule(
        rule_id="DLK-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.SMART_DOOR_LOCK,
        description="Door lock sessions must not exceed 5 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 5.0},
    ),
    PolicyRule(
        rule_id="LHB-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.SMART_LIGHT_HUB,
        description="Light hubs must not use SSH, Telnet, or FTP",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value, Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="LHB-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.SMART_LIGHT_HUB,
        description="Light hubs must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="LHB-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.SMART_LIGHT_HUB,
        description="Light hub bytes_sent must not exceed 15KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 15_000},
    ),
    PolicyRule(
        rule_id="LHB-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.SMART_LIGHT_HUB,
        description="Light hub sessions must not exceed 10 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 10.0},
    ),
    PolicyRule(
        rule_id="TMP-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.TEMPERATURE_SENSOR,
        description="Temperature sensors must not use SSH, Telnet, FTP, or HTTPS",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.SSH.value, Protocol.TELNET.value, Protocol.FTP.value, Protocol.HTTPS.value]},
    ),
    PolicyRule(
        rule_id="TMP-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.TEMPERATURE_SENSOR,
        description="Temperature sensors must stay internal only",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value, DestinationType.TRUSTED_CLOUD.value]},
    ),
    PolicyRule(
        rule_id="TMP-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.TEMPERATURE_SENSOR,
        description="Temp sensor bytes_sent must not exceed 2KB per session",
        confidence=Confidence.HIGH,
        parameters={"field": "bytes_sent", "max_value": 2_000},
    ),
    PolicyRule(
        rule_id="TMP-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.TEMPERATURE_SENSOR,
        description="Temp sensor sessions must not exceed 3 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 3.0},
    ),
    PolicyRule(
        rule_id="GWY-PROTO-001",
        policy_type=PolicyType.PROTOCOL_BLACKLIST,
        device_type=DeviceType.NETWORK_GATEWAY,
        description="Gateways must not use insecure management protocols (Telnet, FTP)",
        confidence=Confidence.HIGH,
        parameters={"blocked_protocols": [Protocol.TELNET.value, Protocol.FTP.value]},
    ),
    PolicyRule(
        rule_id="GWY-DEST-001",
        policy_type=PolicyType.DESTINATION_RESTRICTION,
        device_type=DeviceType.NETWORK_GATEWAY,
        description="Gateways must not contact unknown external destinations",
        confidence=Confidence.HIGH,
        parameters={"blocked_destinations": [DestinationType.UNKNOWN_EXTERNAL.value]},
    ),
    PolicyRule(
        rule_id="GWY-TRAF-001",
        policy_type=PolicyType.TRAFFIC_CEILING,
        device_type=DeviceType.NETWORK_GATEWAY,
        description="Gateway bytes_sent must not exceed 50KB per session",
        confidence=Confidence.MEDIUM,
        parameters={"field": "bytes_sent", "max_value": 50_000},
    ),
    PolicyRule(
        rule_id="GWY-SESS-001",
        policy_type=PolicyType.SESSION_LIMIT,
        device_type=DeviceType.NETWORK_GATEWAY,
        description="Gateway sessions must not exceed 10 seconds",
        confidence=Confidence.MEDIUM,
        parameters={"max_duration": 10.0},
    ),
]
