import { Device, Alert, NetworkEvent, RiskLevel } from './types';

const now = new Date();

function minutesAgo(m: number) {
  return new Date(now.getTime() - m * 60 * 1000);
}

function generateTrustHistory(baseScore: number): { time: string; value: number }[] {
  const points = [];
  for (let i = 29; i >= 0; i--) {
    const t = new Date(now.getTime() - i * 2 * 60 * 1000);
    const noise = (Math.random() - 0.5) * 10;
    points.push({
      time: t.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
      value: Math.max(0, Math.min(100, baseScore + noise)),
    });
  }
  return points;
}

function generateTrafficHistory(baseRate: number): { time: string; value: number }[] {
  const points = [];
  for (let i = 29; i >= 0; i--) {
    const t = new Date(now.getTime() - i * 2 * 60 * 1000);
    const noise = (Math.random() - 0.5) * baseRate * 0.4;
    points.push({
      time: t.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
      value: Math.max(0.1, baseRate + noise),
    });
  }
  return points;
}

function getRiskLevel(score: number): RiskLevel {
  if (score >= 70) return 'safe';
  if (score >= 40) return 'suspicious';
  return 'high-risk';
}

export const initialDevices: Device[] = [
  {
    id: 'dev-001',
    name: 'LAPTOP-ADMIN-01',
    type: 'Laptop',
    ip: '192.168.1.10',
    mac: 'AA:BB:CC:DD:EE:01',
    vendor: 'Dell Technologies',
    trustScore: 92,
    trafficRate: 12.4,
    riskLevel: 'safe',
    lastSeen: minutesAgo(0),
    ports: [80, 443, 22, 8080],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 65 },
      { protocol: 'HTTP', percentage: 15 },
      { protocol: 'SSH', percentage: 12 },
      { protocol: 'DNS', percentage: 8 },
    ],
    trustHistory: generateTrustHistory(92),
    trafficHistory: generateTrafficHistory(12.4),
    os: 'Windows 11 Pro',
    location: 'HQ Floor 2',
  },
  {
    id: 'dev-002',
    name: 'PHONE-USER-07',
    type: 'Phone',
    ip: '192.168.1.34',
    mac: 'AA:BB:CC:DD:EE:02',
    vendor: 'Apple Inc.',
    trustScore: 88,
    trafficRate: 3.2,
    riskLevel: 'safe',
    lastSeen: minutesAgo(1),
    ports: [443, 5228],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 82 },
      { protocol: 'DNS', percentage: 10 },
      { protocol: 'QUIC', percentage: 8 },
    ],
    trustHistory: generateTrustHistory(88),
    trafficHistory: generateTrafficHistory(3.2),
    os: 'iOS 17.3',
    location: 'HQ Floor 1',
  },
  {
    id: 'dev-003',
    name: 'PRINTER-HP-03',
    type: 'Printer',
    ip: '192.168.1.55',
    mac: 'AA:BB:CC:DD:EE:03',
    vendor: 'HP Inc.',
    trustScore: 61,
    trafficRate: 0.8,
    riskLevel: 'suspicious',
    lastSeen: minutesAgo(3),
    ports: [9100, 80, 443, 631],
    protocolUsage: [
      { protocol: 'IPP', percentage: 55 },
      { protocol: 'HTTP', percentage: 30 },
      { protocol: 'SNMP', percentage: 15 },
    ],
    trustHistory: generateTrustHistory(61),
    trafficHistory: generateTrafficHistory(0.8),
    os: 'HP Firmware 3.2',
    location: 'HQ Floor 1',
    flagReason: 'Unusual outbound connections to external IPs detected. Device firmware may need update.',
  },
  {
    id: 'dev-004',
    name: 'SMARTTV-CONF-01',
    type: 'Smart TV',
    ip: '192.168.1.78',
    mac: 'AA:BB:CC:DD:EE:04',
    vendor: 'Samsung Electronics',
    trustScore: 52,
    trafficRate: 15.6,
    riskLevel: 'suspicious',
    lastSeen: minutesAgo(2),
    ports: [8080, 443, 1900],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 45 },
      { protocol: 'SSDP', percentage: 28 },
      { protocol: 'HTTP', percentage: 27 },
    ],
    trustHistory: generateTrustHistory(52),
    trafficHistory: generateTrafficHistory(15.6),
    os: 'Tizen OS 7.0',
    location: 'Conference Room B',
    flagReason: 'High traffic rate anomaly. Device broadcasting on unexpected ports.',
  },
  {
    id: 'dev-005',
    name: 'CAM-LOBBY-21',
    type: 'Security Camera',
    ip: '192.168.1.91',
    mac: 'AA:BB:CC:DD:EE:05',
    vendor: 'Hikvision',
    trustScore: 28,
    trafficRate: 42.1,
    riskLevel: 'high-risk',
    lastSeen: minutesAgo(0),
    ports: [554, 80, 8000, 37777],
    protocolUsage: [
      { protocol: 'RTSP', percentage: 58 },
      { protocol: 'HTTP', percentage: 22 },
      { protocol: 'Unknown', percentage: 20 },
    ],
    trustHistory: generateTrustHistory(28),
    trafficHistory: generateTrafficHistory(42.1),
    os: 'Embedded Linux',
    location: 'Building Lobby',
    flagReason: 'Device trust score dropped significantly. Traffic increased 400% and device started communicating with unknown external server (45.33.21.8). Possible botnet activity.',
  },
  {
    id: 'dev-006',
    name: 'ROUTER-CORE-01',
    type: 'Router',
    ip: '192.168.1.1',
    mac: 'AA:BB:CC:DD:EE:06',
    vendor: 'Cisco Systems',
    trustScore: 95,
    trafficRate: 187.3,
    riskLevel: 'safe',
    lastSeen: minutesAgo(0),
    ports: [22, 80, 443, 161, 179],
    protocolUsage: [
      { protocol: 'BGP', percentage: 35 },
      { protocol: 'OSPF', percentage: 25 },
      { protocol: 'HTTPS', percentage: 20 },
      { protocol: 'SNMP', percentage: 20 },
    ],
    trustHistory: generateTrustHistory(95),
    trafficHistory: generateTrafficHistory(187.3),
    os: 'Cisco IOS XE',
    location: 'Server Room',
  },
  {
    id: 'dev-007',
    name: 'SENSOR-HVAC-04',
    type: 'IoT Sensor',
    ip: '192.168.1.112',
    mac: 'AA:BB:CC:DD:EE:07',
    vendor: 'Honeywell',
    trustScore: 74,
    trafficRate: 0.3,
    riskLevel: 'safe',
    lastSeen: minutesAgo(5),
    ports: [1883, 8883],
    protocolUsage: [
      { protocol: 'MQTT', percentage: 90 },
      { protocol: 'CoAP', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(74),
    trafficHistory: generateTrafficHistory(0.3),
    os: 'FreeRTOS v10.4',
    location: 'HVAC Control Room',
  },
  {
    id: 'dev-008',
    name: 'LAPTOP-DEV-12',
    type: 'Laptop',
    ip: '192.168.1.145',
    mac: 'AA:BB:CC:DD:EE:08',
    vendor: 'Apple Inc.',
    trustScore: 85,
    trafficRate: 28.7,
    riskLevel: 'safe',
    lastSeen: minutesAgo(1),
    ports: [22, 443, 3000, 5000],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 55 },
      { protocol: 'SSH', percentage: 20 },
      { protocol: 'HTTP', percentage: 15 },
      { protocol: 'DNS', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(85),
    trafficHistory: generateTrafficHistory(28.7),
    os: 'macOS Sonoma 14.3',
    location: 'Dev Lab Floor 3',
  },
  {
    id: 'dev-009',
    name: 'SERVER-DB-02',
    type: 'Server',
    ip: '192.168.1.200',
    mac: 'AA:BB:CC:DD:EE:09',
    vendor: 'Dell Technologies',
    trustScore: 90,
    trafficRate: 45.2,
    riskLevel: 'safe',
    lastSeen: minutesAgo(0),
    ports: [5432, 22, 443, 80],
    protocolUsage: [
      { protocol: 'PostgreSQL', percentage: 60 },
      { protocol: 'HTTPS', percentage: 25 },
      { protocol: 'SSH', percentage: 15 },
    ],
    trustHistory: generateTrustHistory(90),
    trafficHistory: generateTrafficHistory(45.2),
    os: 'Ubuntu 22.04 LTS',
    location: 'Data Center',
  },
  {
    id: 'dev-010',
    name: 'TABLET-SALES-09',
    type: 'Tablet',
    ip: '192.168.1.167',
    mac: 'AA:BB:CC:DD:EE:0A',
    vendor: 'Microsoft',
    trustScore: 45,
    trafficRate: 7.8,
    riskLevel: 'suspicious',
    lastSeen: minutesAgo(8),
    ports: [443, 3389],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 60 },
      { protocol: 'RDP', percentage: 30 },
      { protocol: 'DNS', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(45),
    trafficHistory: generateTrafficHistory(7.8),
    os: 'Windows 11 Home',
    location: 'Sales Office',
    flagReason: 'RDP port detected active on a tablet device. Unauthorized remote desktop usage suspected.',
  },
  {
    id: 'dev-011',
    name: 'CAM-PARKING-03',
    type: 'Security Camera',
    ip: '192.168.1.183',
    mac: 'AA:BB:CC:DD:EE:0B',
    vendor: 'Dahua Technology',
    trustScore: 35,
    trafficRate: 18.4,
    riskLevel: 'high-risk',
    lastSeen: minutesAgo(2),
    ports: [554, 37777, 80],
    protocolUsage: [
      { protocol: 'RTSP', percentage: 50 },
      { protocol: 'Unknown', percentage: 35 },
      { protocol: 'HTTP', percentage: 15 },
    ],
    trustHistory: generateTrustHistory(35),
    trafficHistory: generateTrafficHistory(18.4),
    os: 'Embedded Linux',
    location: 'Parking Lot',
    flagReason: 'Device performing port scanning activity on internal network. Potential compromise detected.',
  },
  {
    id: 'dev-012',
    name: 'SENSOR-DOOR-07',
    type: 'IoT Sensor',
    ip: '192.168.1.221',
    mac: 'AA:BB:CC:DD:EE:0C',
    vendor: 'Bosch Security',
    trustScore: 82,
    trafficRate: 0.1,
    riskLevel: 'safe',
    lastSeen: minutesAgo(3),
    ports: [8883],
    protocolUsage: [
      { protocol: 'MQTT', percentage: 100 },
    ],
    trustHistory: generateTrustHistory(82),
    trafficHistory: generateTrafficHistory(0.1),
    os: 'Zephyr RTOS',
    location: 'Main Entrance',
  },
  {
    id: 'dev-013',
    name: 'PHONE-GUEST-14',
    type: 'Phone',
    ip: '192.168.2.45',
    mac: 'AA:BB:CC:DD:EE:0D',
    vendor: 'Samsung Electronics',
    trustScore: 55,
    trafficRate: 4.9,
    riskLevel: 'suspicious',
    lastSeen: minutesAgo(15),
    ports: [443, 5228, 80],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 70 },
      { protocol: 'HTTP', percentage: 20 },
      { protocol: 'DNS', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(55),
    trafficHistory: generateTrafficHistory(4.9),
    os: 'Android 14',
    location: 'Guest WiFi',
    flagReason: 'Device connected to guest network attempting to access internal resources.',
  },
  {
    id: 'dev-014',
    name: 'LAPTOP-FIN-22',
    type: 'Laptop',
    ip: '192.168.1.98',
    mac: 'AA:BB:CC:DD:EE:0E',
    vendor: 'Lenovo',
    trustScore: 78,
    trafficRate: 9.3,
    riskLevel: 'safe',
    lastSeen: minutesAgo(4),
    ports: [443, 80, 8443],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 78 },
      { protocol: 'HTTP', percentage: 12 },
      { protocol: 'DNS', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(78),
    trafficHistory: generateTrafficHistory(9.3),
    os: 'Windows 11 Pro',
    location: 'Finance Dept',
  },
  {
    id: 'dev-015',
    name: 'SERVER-WEB-01',
    type: 'Server',
    ip: '192.168.1.250',
    mac: 'AA:BB:CC:DD:EE:0F',
    vendor: 'HP Inc.',
    trustScore: 88,
    trafficRate: 124.6,
    riskLevel: 'safe',
    lastSeen: minutesAgo(0),
    ports: [80, 443, 22, 8080],
    protocolUsage: [
      { protocol: 'HTTPS', percentage: 65 },
      { protocol: 'HTTP', percentage: 25 },
      { protocol: 'SSH', percentage: 10 },
    ],
    trustHistory: generateTrustHistory(88),
    trafficHistory: generateTrafficHistory(124.6),
    os: 'CentOS Stream 9',
    location: 'Data Center',
  },
];

export const initialAlerts: Alert[] = [
  {
    id: 'alert-001',
    type: 'Traffic Anomaly',
    deviceId: 'dev-005',
    deviceName: 'CAM-LOBBY-21',
    severity: 'critical',
    timestamp: minutesAgo(5),
    message: 'Outbound traffic increased by 400%. Device contacting unknown external server 45.33.21.8.',
    read: false,
  },
  {
    id: 'alert-002',
    type: 'Port Scan Detected',
    deviceId: 'dev-011',
    deviceName: 'CAM-PARKING-03',
    severity: 'high',
    timestamp: minutesAgo(12),
    message: 'Device performing horizontal port scan across internal subnet 192.168.1.0/24.',
    read: false,
  },
  {
    id: 'alert-003',
    type: 'Trust Score Drop',
    deviceId: 'dev-004',
    deviceName: 'SMARTTV-CONF-01',
    severity: 'medium',
    timestamp: minutesAgo(18),
    message: 'Trust score dropped from 75 to 52. Unusual SSDP broadcast activity detected.',
    read: false,
  },
  {
    id: 'alert-004',
    type: 'Policy Violation',
    deviceId: 'dev-010',
    deviceName: 'TABLET-SALES-09',
    severity: 'high',
    timestamp: minutesAgo(25),
    message: 'RDP connection initiated from tablet device. Policy prohibits remote desktop on mobile devices.',
    read: true,
  },
  {
    id: 'alert-005',
    type: 'Unauthorized Access Attempt',
    deviceId: 'dev-013',
    deviceName: 'PHONE-GUEST-14',
    severity: 'medium',
    timestamp: minutesAgo(33),
    message: 'Guest network device attempting to reach internal resource at 192.168.1.200.',
    read: true,
  },
];

export const initialEvents: NetworkEvent[] = [
  {
    id: 'evt-001',
    time: minutesAgo(2),
    deviceId: 'dev-005',
    deviceName: 'CAM-LOBBY-21',
    type: 'anomaly',
    description: 'Traffic spike detected: 42.1 Mbps outbound (baseline: 8.2 Mbps)',
  },
  {
    id: 'evt-002',
    time: minutesAgo(5),
    deviceId: 'dev-005',
    deviceName: 'CAM-LOBBY-21',
    type: 'new_connection',
    description: 'New outbound connection established to 45.33.21.8:4444',
  },
  {
    id: 'evt-003',
    time: minutesAgo(10),
    deviceId: 'dev-011',
    deviceName: 'CAM-PARKING-03',
    type: 'scan_detected',
    description: 'Port scan detected: 192.168.1.0/24 range, 1024 ports probed',
  },
  {
    id: 'evt-004',
    time: minutesAgo(15),
    deviceId: 'dev-003',
    deviceName: 'PRINTER-HP-03',
    type: 'trust_update',
    description: 'Trust score updated: 75 → 61 due to unexpected external connections',
  },
  {
    id: 'evt-005',
    time: minutesAgo(18),
    deviceId: 'dev-004',
    deviceName: 'SMARTTV-CONF-01',
    type: 'policy_violation',
    description: 'SSDP discovery broadcast detected on external-facing interface',
  },
  {
    id: 'evt-006',
    time: minutesAgo(22),
    deviceId: 'dev-013',
    deviceName: 'PHONE-GUEST-14',
    type: 'new_connection',
    description: 'Guest device attempting connection to internal server 192.168.1.200',
  },
  {
    id: 'evt-007',
    time: minutesAgo(30),
    deviceId: 'dev-010',
    deviceName: 'TABLET-SALES-09',
    type: 'policy_violation',
    description: 'RDP session initiated — violates mobile device policy',
  },
  {
    id: 'evt-008',
    time: minutesAgo(45),
    deviceId: 'dev-014',
    deviceName: 'LAPTOP-FIN-22',
    type: 'device_joined',
    description: 'Device connected to network and authenticated successfully',
  },
];
